/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Stocks */
        get: operations["search_stocks_api_v1_stocks_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock */
        get: operations["get_stock_api_v1_stocks__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/daily-bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Daily Bars */
        get: operations["get_daily_bars_api_v1_stocks__symbol__daily_bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlists */
        get: operations["list_watchlists_api_v1_watchlists_get"];
        put?: never;
        /** Create Watchlist */
        post: operations["create_watchlist_api_v1_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Watchlist Item */
        post: operations["add_watchlist_item_api_v1_watchlists__watchlist_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddWatchlistItemRequest */
        AddWatchlistItemRequest: {
            /** Symbol */
            symbol: string;
        };
        /** CreateWatchlistRequest */
        CreateWatchlistRequest: {
            /** Name */
            name: string;
        };
        /** DailyBarListResponse */
        DailyBarListResponse: {
            /** Symbol */
            symbol: string;
            /** Canonical Symbol */
            canonical_symbol: string;
            /** Adjust */
            adjust: string;
            /** Items */
            items: components["schemas"]["DailyBarResponse"][];
            /** Total */
            total: number;
        };
        /** DailyBarResponse */
        DailyBarResponse: {
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Adjust Type */
            adjust_type: string;
            /** Open */
            open: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Close */
            close: string;
            /** Pre Close */
            pre_close: string | null;
            /** Volume */
            volume: number;
            /** Amount */
            amount: string;
            /** Pct Change */
            pct_change: string | null;
            /** Source */
            source: string;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** StockResponse */
        StockResponse: {
            /** Symbol */
            symbol: string;
            /** Canonical Symbol */
            canonical_symbol: string;
            /** Name */
            name: string;
            /** Exchange */
            exchange: string;
            /** Board */
            board: string;
            /** Asset Type */
            asset_type: string;
            /** List Date */
            list_date: string | null;
            /** Status */
            status: string;
            /** Industry */
            industry: string | null;
            /** Latest Price */
            latest_price: string | null;
            /** Change Percent */
            change_percent: string | null;
            /** Latest Trade Date */
            latest_trade_date: string | null;
            /** Source */
            source: string | null;
            /** Collected At */
            collected_at: string | null;
        };
        /** StockSearchResponse */
        StockSearchResponse: {
            /** Items */
            items: components["schemas"]["StockResponse"][];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistItemResponse */
        WatchlistItemResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /** WatchlistResponse */
        WatchlistResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Items */
            items: components["schemas"]["WatchlistItemResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_stocks_api_v1_stocks_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_api_v1_stocks__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_bars_api_v1_stocks__symbol__daily_bars_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                limit?: number;
                adjust?: "none";
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyBarListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlists_api_v1_watchlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"][];
                };
            };
        };
    };
    create_watchlist_api_v1_watchlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWatchlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_watchlist_item_api_v1_watchlists__watchlist_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWatchlistItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
