/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Stocks */
        get: operations["search_stocks_api_v1_stocks_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock */
        get: operations["get_stock_api_v1_stocks__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/daily-bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Daily Bars */
        get: operations["get_daily_bars_api_v1_stocks__symbol__daily_bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/research/fundamentals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fundamental Research */
        get: operations["get_fundamental_research_api_v1_stocks__symbol__research_fundamentals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/research/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research Snapshot */
        get: operations["get_research_snapshot_api_v1_stocks__symbol__research_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/research/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Observations */
        get: operations["list_research_observations_api_v1_stocks__symbol__research_observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/research/observations/{observation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research Observation */
        get: operations["get_research_observation_api_v1_stocks__symbol__research_observations__observation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/financials/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Financial Periods */
        get: operations["get_financial_periods_api_v1_stocks__symbol__financials_periods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{symbol}/valuations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Valuations */
        get: operations["get_valuations_api_v1_stocks__symbol__valuations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlists */
        get: operations["list_watchlists_api_v1_watchlists_get"];
        put?: never;
        /** Create Watchlist */
        post: operations["create_watchlist_api_v1_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{watchlist_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Watchlist Item */
        post: operations["add_watchlist_item_api_v1_watchlists__watchlist_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddWatchlistItemRequest */
        AddWatchlistItemRequest: {
            /** Symbol */
            symbol: string;
        };
        /**
         * AttentionLevel
         * @enum {string}
         */
        AttentionLevel: "info" | "notice" | "important";
        /** BalanceSheetResponse */
        BalanceSheetResponse: {
            /** Cash */
            cash: string | null;
            /** Accounts Receivable */
            accounts_receivable: string | null;
            /** Inventory */
            inventory: string | null;
            /** Current Assets */
            current_assets: string | null;
            /** Total Assets */
            total_assets: string | null;
            /** Current Liabilities */
            current_liabilities: string | null;
            /** Total Liabilities */
            total_liabilities: string | null;
            /** Parent Equity */
            parent_equity: string | null;
            /** Total Equity */
            total_equity: string | null;
            /** Goodwill */
            goodwill: string | null;
        };
        /** CalculationTrace */
        CalculationTrace: {
            /** Method */
            method: string;
            /** Expression */
            expression: string;
            /** Change Value */
            change_value?: string | null;
            /** Change Unit */
            change_unit?: string | null;
        };
        /** CashFlowStatementResponse */
        CashFlowStatementResponse: {
            /** Operating Cash Flow */
            operating_cash_flow: string | null;
            /** Investing Cash Flow */
            investing_cash_flow: string | null;
            /** Financing Cash Flow */
            financing_cash_flow: string | null;
            /** Cash Paid For Long Term Assets */
            cash_paid_for_long_term_assets: string | null;
            /** Ending Cash */
            ending_cash: string | null;
        };
        /**
         * CoverageStatus
         * @enum {string}
         */
        CoverageStatus: "available" | "missing" | "not_applicable" | "insufficient_history" | "provider_unavailable";
        /** CreateWatchlistRequest */
        CreateWatchlistRequest: {
            /** Name */
            name: string;
        };
        /** DailyBarListResponse */
        DailyBarListResponse: {
            /** Symbol */
            symbol: string;
            /** Canonical Symbol */
            canonical_symbol: string;
            /** Adjust */
            adjust: string;
            /** Items */
            items: components["schemas"]["DailyBarResponse"][];
            /** Total */
            total: number;
        };
        /** DailyBarResponse */
        DailyBarResponse: {
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Adjust Type */
            adjust_type: string;
            /** Open */
            open: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Close */
            close: string;
            /** Pre Close */
            pre_close: string | null;
            /** Volume */
            volume: number;
            /** Amount */
            amount: string;
            /** Pct Change */
            pct_change: string | null;
            /** Source */
            source: string;
            /**
             * Collected At
             * Format: date-time
             */
            collected_at: string;
        };
        /** EvidenceMetric */
        EvidenceMetric: {
            /**
             * Metric Point Id
             * Format: uuid
             */
            metric_point_id: string;
            /** Role */
            role: string;
            /** Metric Code */
            metric_code: string;
            /** Display Name */
            display_name: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Fiscal Period */
            fiscal_period: string;
            /** Basis */
            basis: string;
            /** Value */
            value: string | null;
            /** Unit */
            unit: string;
            /** Status */
            status: string;
            /** Input Report Ids */
            input_report_ids?: string[];
            /** Input Valuation Ids */
            input_valuation_ids?: string[];
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /** EvidenceSource */
        EvidenceSource: {
            /**
             * Report Id
             * Format: uuid
             */
            report_id: string;
            /** Provider */
            provider: string;
            /** Provider Record Id */
            provider_record_id: string;
            /** Fiscal Period */
            fiscal_period: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Published At Precision */
            published_at_precision: string;
            /**
             * Known At
             * Format: date-time
             */
            known_at: string;
        };
        /** FinancialPeriodListResponse */
        FinancialPeriodListResponse: {
            /** Symbol */
            symbol: string;
            /** Canonical Symbol */
            canonical_symbol: string;
            /** Items */
            items: components["schemas"]["FinancialPeriodResponse"][];
            /** Total */
            total: number;
        };
        /** FinancialPeriodResponse */
        FinancialPeriodResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Fiscal Year */
            fiscal_year: number;
            /** Fiscal Period */
            fiscal_period: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Statement Scope */
            statement_scope: string;
            /** Currency */
            currency: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Published At Precision */
            published_at_precision: string;
            /**
             * Known At
             * Format: date-time
             */
            known_at: string;
            /** Is Audited */
            is_audited: boolean | null;
            /** Provider */
            provider: string;
            /** Provider Revision */
            provider_revision: string;
            /** Normalizer Version */
            normalizer_version: string;
            /** Quality Warnings */
            quality_warnings: string[];
            income: components["schemas"]["IncomeStatementResponse"] | null;
            balance: components["schemas"]["BalanceSheetResponse"] | null;
            cash_flow: components["schemas"]["CashFlowStatementResponse"] | null;
        };
        /** FundamentalDimensionResponse */
        FundamentalDimensionResponse: {
            /** Code */
            code: string;
            /** Display Name */
            display_name: string;
            /** Items */
            items: components["schemas"]["FundamentalMetricResponse"][];
        };
        /** FundamentalMetricResponse */
        FundamentalMetricResponse: {
            /** Code */
            code: string;
            /** Display Name */
            display_name: string;
            /** Dimension */
            dimension: string;
            /** Value */
            value: string | null;
            /** Unit */
            unit: string;
            /** Status */
            status: string;
            /** Period End */
            period_end: string | null;
            /** Basis */
            basis: string;
            /** Source Report Ids */
            source_report_ids: string[];
            /** Detail */
            detail: string | null;
        };
        /** FundamentalResearchResponse */
        FundamentalResearchResponse: {
            /** Symbol */
            symbol: string;
            /** Canonical Symbol */
            canonical_symbol: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Latest Report Period */
            latest_report_period: string | null;
            /** Latest Report Published At */
            latest_report_published_at: string | null;
            /** Published At Precision */
            published_at_precision: string | null;
            /** Issuer Type */
            issuer_type: string;
            /** Provider */
            provider: string | null;
            /** Data Version */
            data_version: string;
            /** Metric Definition Version */
            metric_definition_version: string;
            /** Freshness */
            freshness: string;
            /** Dimensions */
            dimensions: components["schemas"]["FundamentalDimensionResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** IncomeStatementResponse */
        IncomeStatementResponse: {
            /** Revenue */
            revenue: string | null;
            /** Operating Cost */
            operating_cost: string | null;
            /** Operating Profit */
            operating_profit: string | null;
            /** Total Profit */
            total_profit: string | null;
            /** Net Profit */
            net_profit: string | null;
            /** Parent Net Profit */
            parent_net_profit: string | null;
        };
        /**
         * Movement
         * @enum {string}
         */
        Movement: "up" | "down" | "crossed_up" | "crossed_down" | "neutral";
        /**
         * ObservationDimension
         * @enum {string}
         */
        ObservationDimension: "growth" | "profitability" | "quality" | "balance" | "valuation";
        /** ObservationList */
        ObservationList: {
            /** Symbol */
            symbol: string;
            /** Snapshot Id */
            snapshot_id: string | null;
            /** Items */
            items: components["schemas"]["ResearchObservation"][];
            /** Total */
            total: number;
        };
        /** ResearchCoverage */
        ResearchCoverage: {
            dimension: components["schemas"]["ObservationDimension"];
            status: components["schemas"]["CoverageStatus"];
            /** Reason */
            reason?: string | null;
        };
        /** ResearchObservation */
        ResearchObservation: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Symbol */
            symbol: string;
            dimension: components["schemas"]["ObservationDimension"];
            /** Observation Family */
            observation_family: string;
            /** Observation Type */
            observation_type: string;
            attention_level: components["schemas"]["AttentionLevel"];
            movement: components["schemas"]["Movement"];
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /**
             * Current Period
             * Format: date
             */
            current_period: string;
            /** Comparison Periods */
            comparison_periods: string[];
            /** Rule Id */
            rule_id: string;
            /** Rule Version */
            rule_version: string;
            /** Observation Key */
            observation_key: string;
            /** Content Fingerprint */
            content_fingerprint: string;
            /** Evidence Metrics */
            evidence_metrics: components["schemas"]["EvidenceMetric"][];
            /** Evidence Sources */
            evidence_sources: components["schemas"]["EvidenceSource"][];
            calculation: components["schemas"]["CalculationTrace"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** ResearchSnapshotDocument */
        ResearchSnapshotDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Symbol */
            symbol: string;
            /**
             * Knowledge Cutoff
             * Format: date-time
             */
            knowledge_cutoff: string;
            /** Data Version */
            data_version: string;
            /** Metric Version */
            metric_version: string;
            /** Rule Set Version */
            rule_set_version: string;
            /** Research Template Version */
            research_template_version: string;
            /** Snapshot Schema Version */
            snapshot_schema_version: string;
            /**
             * Producer Kind
             * @default deterministic
             * @constant
             */
            producer_kind: "deterministic";
            /** Producer Version */
            producer_version: string;
            /** Latest Financial Period */
            latest_financial_period: string | null;
            /** Latest Valuation Date */
            latest_valuation_date: string | null;
            /** Input Manifest */
            input_manifest: {
                [key: string]: unknown;
            };
            /** Coverage */
            coverage: components["schemas"]["ResearchCoverage"][];
            /** Observations */
            observations: components["schemas"]["ResearchObservation"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** ResearchSnapshotEnvelope */
        ResearchSnapshotEnvelope: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_built";
            snapshot?: components["schemas"]["ResearchSnapshotDocument"] | null;
        };
        /** StockResponse */
        StockResponse: {
            /** Symbol */
            symbol: string;
            /** Canonical Symbol */
            canonical_symbol: string;
            /** Name */
            name: string;
            /** Exchange */
            exchange: string;
            /** Board */
            board: string;
            /** Asset Type */
            asset_type: string;
            /** List Date */
            list_date: string | null;
            /** Status */
            status: string;
            /** Issuer Type */
            issuer_type: string;
            /** Industry */
            industry: string | null;
            /** Latest Price */
            latest_price: string | null;
            /** Change Percent */
            change_percent: string | null;
            /** Latest Trade Date */
            latest_trade_date: string | null;
            /** Source */
            source: string | null;
            /** Collected At */
            collected_at: string | null;
        };
        /** StockSearchResponse */
        StockSearchResponse: {
            /** Items */
            items: components["schemas"]["StockResponse"][];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValuationCoverageResponse */
        ValuationCoverageResponse: {
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Sample Count */
            sample_count: number;
            /** Metric Codes */
            metric_codes: string[];
        };
        /** ValuationListResponse */
        ValuationListResponse: {
            /** Symbol */
            symbol: string;
            /** Canonical Symbol */
            canonical_symbol: string;
            /** Items */
            items: components["schemas"]["ValuationObservationResponse"][];
            /** Total */
            total: number;
            coverage: components["schemas"]["ValuationCoverageResponse"];
        };
        /** ValuationObservationResponse */
        ValuationObservationResponse: {
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Metric Code */
            metric_code: string;
            /** Value */
            value: string;
            /** Unit */
            unit: string;
            /** Provider */
            provider: string;
        };
        /** WatchlistItemResponse */
        WatchlistItemResponse: {
            /** Symbol */
            symbol: string;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /** WatchlistResponse */
        WatchlistResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Items */
            items: components["schemas"]["WatchlistItemResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_stocks_api_v1_stocks_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_api_v1_stocks__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_bars_api_v1_stocks__symbol__daily_bars_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                limit?: number;
                adjust?: "none";
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyBarListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fundamental_research_api_v1_stocks__symbol__research_fundamentals_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundamentalResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_snapshot_api_v1_stocks__symbol__research_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSnapshotEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_observations_api_v1_stocks__symbol__research_observations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_observation_api_v1_stocks__symbol__research_observations__observation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
                observation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchObservation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_financial_periods_api_v1_stocks__symbol__financials_periods_get: {
        parameters: {
            query?: {
                as_of?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialPeriodListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_valuations_api_v1_stocks__symbol__valuations_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                metrics?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValuationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlists_api_v1_watchlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"][];
                };
            };
        };
    };
    create_watchlist_api_v1_watchlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWatchlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_watchlist_item_api_v1_watchlists__watchlist_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWatchlistItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
